version: '3'
services:
    postgres:
        image: postgres:16.2-bullseye
        environment:
            - POSTGRES_PASSWORD=admin
            - POSTGRES_USER=admin
            - POSTGRES_DB=default
        ports:
            - 5444:5432
        volumes:
            - ./postgres/data:/var/lib/postgresql/data
            - ./postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
